"""
Style Adherence Evaluation for IndicParler-TTS Long-Form Expression

Computes L_sem (semantic alignment) and L_dyn (dynamic style smoothness)
metrics from the proposal for evaluating style adherence in generated speech.

Usage:
    python evaluate_style_adherence.py

Requirements:
    - style_captions.json (generated by generate_captions.py)
    - IndicParler-TTS model loaded
    - StoricoTTSDataset/test.csv
"""

import os
import json
import csv
import torch
import numpy as np
import soundfile as sf
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer
from parler_tts import ParlerTTSForConditionalGeneration
import warnings
import librosa

warnings.filterwarnings("ignore")

# ============================================================================
# Configuration
# ============================================================================

MODEL_NAME = "ai4bharat/indic-parler-tts"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
CLAP_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

DATA_DIR = "StoricoTTSDataset"
CLIPS_DIR = os.path.join(DATA_DIR, "clips")
CAPTIONS_FILE = os.path.join(DATA_DIR, "style_captions.json")
TEST_CSV = os.path.join(DATA_DIR, "test.csv")
OUTPUT_DIR = "evaluation_output"
GENERATED_AUDIO_DIR = os.path.join(OUTPUT_DIR, "generated")

# Create output directories
os.makedirs(GENERATED_AUDIO_DIR, exist_ok=True)

# Set to True for quick test with 1 story (5 segments)
# Set to False for full evaluation on all test segments
QUICK_TEST = False
QUICK_TEST_STORY = "23"
QUICK_TEST_LIMIT = 5

# ============================================================================
# Model Loading
# ============================================================================


def load_clap_model(device=CLAP_DEVICE):
    """Load CLAP model for joint text-audio embeddings."""
    try:
        from transformers import ClapModel, ClapProcessor
        
        print("Loading CLAP model for L_sem evaluation...")
        clap_model = ClapModel.from_pretrained("laion/larger_clap_general").to(device)
        clap_processor = ClapProcessor.from_pretrained("laion/larger_clap_general")
        print("CLAP model loaded successfully!")
        return clap_model, clap_processor
    except Exception as e:
        print(f"Warning: Could not load CLAP model: {e}")
        print("L_sem will be computed using fallback method")
        return None, None


def load_model(model_name=MODEL_NAME, device=DEVICE):
    """Load IndicParler-TTS model and tokenizers."""
    print(f"Loading model: {model_name}")
    print(f"Device: {device}")

    model = ParlerTTSForConditionalGeneration.from_pretrained(
        model_name,
        torch_dtype="auto",
        low_cpu_mem_usage=True,
    ).to(device)

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    description_tokenizer = AutoTokenizer.from_pretrained(
        model.config.text_encoder._name_or_path
    )

    print("Model loaded successfully!")
    return model, tokenizer, description_tokenizer, device


# ============================================================================
# Data Loading
# ============================================================================


def load_test_segments():
    """Load test.csv segments with metadata."""
    segments = []
    with open(TEST_CSV, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            segments.append({
                'segment_id': os.path.basename(row['audio_filepath']).replace('.wav', ''),
                'audio_filepath': row['audio_filepath'],
                'character': row.get('character', '').strip(),
                'emotion': row.get('emotion', '').strip(),
                'text': row.get('text', ''),
                'story': row.get('story', ''),
            })
    return segments


def load_style_captions():
    """Load GPT-4o generated style captions."""
    with open(CAPTIONS_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def get_style_caption_for_segment(segment_id, style_captions, segment):
    """
    Get style caption for a segment, with fallbacks for missing/failed captions.
    
    Priority:
    1. Use GPT-4o generated caption (if successful)
    2. Use existing emotion annotation (if available)
    3. Use character/narrator template
    4. Use default fallback
    """
    # Check if we have a generated caption
    caption_data = style_captions.get(segment_id, {})
    style_caption = caption_data.get('style_caption', '')
    
    # Check if caption failed
    if not style_caption or style_caption.startswith('[ERROR]'):
        # Fallback 1: Use existing emotion annotation
        if segment.get('emotion'):
            emotion = segment['emotion']
            # Convert Hindi emotion to English caption
            return f"spoken with emotion: {emotion}"
        
        # Fallback 2: Character vs narrator template
        if segment.get('character'):
            return "spoken expressively, character dialogue"
        else:
            return "spoken calmly, neutral narrator style"
    
    # Check if it's an [EXISTING] annotation
    if style_caption.startswith('[EXISTING]'):
        emotion = style_caption.replace('[EXISTING]', '').strip()
        return f"spoken with emotion: {emotion}"
    
    return style_caption


def group_segments_by_story(segments):
    """Group segments by story for L_dyn computation."""
    stories = {}
    for seg in segments:
        story_id = seg['story']
        if story_id not in stories:
            stories[story_id] = []
        stories[story_id].append(seg)
    
    # Sort each story by segment index
    for story_id in stories:
        stories[story_id].sort(
            key=lambda x: int(x['segment_id'].split('_')[-1])
        )
    
    return stories


# ============================================================================
# Speech Generation
# ============================================================================


def generate_speech(model, tokenizer, description_tokenizer, device,
                    text, style_caption, output_path):
    """Generate speech using IndicParler-TTS."""

    # Clean up style caption (remove [EXISTING] prefix if present)
    if style_caption.startswith('[EXISTING]'):
        style_caption = style_caption.replace('[EXISTING]', '').strip()
    elif style_caption.startswith('[ERROR]'):
        style_caption = "neutral narration, clear speech"

    # Tokenize with proper tokenizers
    # description_tokenizer (T5) for English style captions
    # tokenizer (main) for Hindi transcript
    description_input_ids = description_tokenizer(
        style_caption, return_tensors="pt"
    ).to(device)
    prompt_input_ids = tokenizer(text, return_tensors="pt").to(device)

    # Generate
    with torch.no_grad():
        generation = model.generate(
            input_ids=description_input_ids.input_ids,
            attention_mask=description_input_ids.attention_mask,
            prompt_input_ids=prompt_input_ids.input_ids,
            prompt_attention_mask=prompt_input_ids.attention_mask,
        )

    # Convert to audio array
    audio_arr = generation.cpu().numpy().squeeze()
    
    # Validate audio array
    if audio_arr.ndim == 0 or audio_arr.size == 0:
        raise ValueError(f"Generated audio is empty or invalid. Shape: {audio_arr.shape}")
    
    # Ensure 1D array for mono audio
    if audio_arr.ndim > 1:
        audio_arr = audio_arr.mean(axis=0)  # Convert to mono if multi-channel

    # Save
    sf.write(output_path, audio_arr, model.config.sampling_rate)
    return output_path


# ============================================================================
# Embedding Extraction
# ============================================================================


def extract_style_embedding(model, device, audio_path):
    """
    Extract style embedding from generated audio using CLAP.
    CLAP provides joint text-audio embeddings in the same space.
    """
    # Load audio
    audio_arr, sr = sf.read(audio_path)

    # Resample to 48kHz for CLAP
    if sr != 48000:
        audio_arr = librosa.resample(audio_arr, orig_sr=sr, target_sr=48000)

    return audio_arr  # Return raw audio for CLAP processing


def extract_caption_embedding(model, description_tokenizer, device, style_caption):
    """
    Extract style embedding from text caption.
    Returns the caption text for CLAP processing.
    """
    # Clean caption
    if style_caption.startswith('[EXISTING]'):
        style_caption = style_caption.replace('[EXISTING]', '').strip()
    elif style_caption.startswith('[ERROR]'):
        style_caption = "neutral narration"

    return style_caption  # Return text for CLAP processing


def compute_l_sem_clap(clap_model, clap_processor, device, caption_text, audio_arr):
    """
    Compute L_sem using CLAP model.
    
    CLAP is trained to align text and audio embeddings, so we can directly
    compute cosine similarity between them.
    """
    # Process text
    text_inputs = clap_processor(
        text=[caption_text],
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=77
    ).to(device)
    
    # Process audio
    audio_inputs = clap_processor(
        audios=[audio_arr],
        return_tensors="pt",
        padding=True,
        sampling_rate=48000
    ).to(device)
    
    # Get embeddings
    with torch.no_grad():
        text_features = clap_model.get_text_features(**text_inputs)
        audio_features = clap_model.get_audio_features(**audio_inputs)
    
    # Normalize
    text_features = text_features / text_features.norm(dim=-1, keepdim=True)
    audio_features = audio_features / audio_features.norm(dim=-1, keepdim=True)
    
    # Cosine similarity (higher = better alignment)
    similarity = (text_features @ audio_features.T).item()
    
    return similarity


def extract_clap_audio_embedding(clap_model, clap_processor, device, audio_arr):
    """
    Extract audio embedding using CLAP for L_dyn computation.
    """
    audio_inputs = clap_processor(
        audios=[audio_arr],
        return_tensors="pt",
        padding=True,
        sampling_rate=48000
    ).to(device)
    
    with torch.no_grad():
        audio_features = clap_model.get_audio_features(**audio_inputs)
    
    # Normalize
    audio_features = audio_features / audio_features.norm(dim=-1, keepdim=True)
    
    return audio_features.cpu().numpy()


# ============================================================================
# Metrics Computation
# ============================================================================


def compute_l_dyn(audio_embeddings):
    """
    L_dyn: Dynamic style smoothness across consecutive segments.
    
    Formula: (1/K-1) * Σ ||emb_{i+1} - emb_i||²
    
    Lower = smoother transitions (better consistency)
    """
    if len(audio_embeddings) < 2:
        return 0.0
    
    embeddings = np.array(audio_embeddings)
    
    # Compute consecutive deltas
    deltas = np.diff(embeddings, axis=0)
    
    # L2 norm squared for each transition
    delta_magnitudes = np.linalg.norm(deltas, axis=1) ** 2
    
    # Average
    return float(np.mean(delta_magnitudes))


# ============================================================================
# Evaluation Pipeline
# ============================================================================


def evaluate_segment(model, tokenizer, description_tokenizer, clap_model, clap_processor, device, segment, style_caption,
                     generated_audio_path):
    """
    Evaluate a single segment: generate audio and compute L_sem.

    Returns:
        dict with l_sem score and metadata
    """
    segment_id = segment['segment_id']
    text = segment['text']

    # Generate audio
    try:
        generate_speech(
            model=model,
            tokenizer=tokenizer,
            description_tokenizer=description_tokenizer,
            device=device,
            text=text,
            style_caption=style_caption,
            output_path=generated_audio_path,
        )
    except Exception as e:
        import traceback
        error_details = traceback.format_exc()
        print(f"Generation error for {segment_id}: {error_details}")
        return {
            'segment_id': segment_id,
            'l_sem': None,
            'error': str(e),
            'style_caption': style_caption,
        }

    # Compute L_sem using CLAP
    try:
        # Load generated audio
        audio_arr, sr = sf.read(generated_audio_path)
        
        # Resample for CLAP
        if sr != 48000:
            audio_arr = librosa.resample(audio_arr, orig_sr=sr, target_sr=48000)
        
        # Compute L_sem using CLAP
        if clap_model is not None:
            l_sem = compute_l_sem_clap(
                clap_model, clap_processor, device, style_caption, audio_arr
            )
        else:
            # Fallback: set to None if CLAP not available
            l_sem = None
    except Exception as e:
        return {
            'segment_id': segment_id,
            'l_sem': None,
            'error': f"L_sem computation failed: {str(e)}",
            'style_caption': style_caption,
        }

    return {
        'segment_id': segment_id,
        'l_sem': l_sem,
        'style_caption': style_caption,
        'character': segment['character'],
        'story': segment['story'],
        'generated_audio': generated_audio_path,
    }


def evaluate_story(model, tokenizer, description_tokenizer, clap_model, clap_processor, device, story_segments, style_captions):
    """
    Evaluate a complete story: compute L_dyn across all segments.

    Returns:
        dict with l_dyn score and per-segment l_sem scores
    """
    story_id = story_segments[0]['story']
    results = {
        'story_id': story_id,
        'segments': [],
        'l_dyn': None,
        'l_sem_avg': None,
        'caption_stats': {
            'total': len(story_segments),
            'gpt4o_generated': 0,
            'fallback_emotion': 0,
            'fallback_template': 0,
            'failed': 0,
        }
    }

    audio_embeddings = []
    l_sem_scores = []

    print(f"\nEvaluating Story {story_id} ({len(story_segments)} segments)...")

    for seg in tqdm(story_segments, desc=f"Story {story_id}", unit="seg"):
        segment_id = seg['segment_id']
        
        # Get caption with fallback logic
        caption_data = style_captions.get(segment_id, {})
        raw_caption = caption_data.get('style_caption', '')
        
        # Track caption source (per segment)
        caption_source = 'unknown'
        if raw_caption and not raw_caption.startswith('[ERROR]') and not raw_caption.startswith('[EXISTING]'):
            results['caption_stats']['gpt4o_generated'] += 1
            caption_source = 'gpt4o'
        elif raw_caption.startswith('[EXISTING]') or seg.get('emotion'):
            results['caption_stats']['fallback_emotion'] += 1
            caption_source = 'emotion_fallback'
        elif raw_caption.startswith('[ERROR]') or not raw_caption:
            results['caption_stats']['failed'] += 1
            caption_source = 'error_or_missing'
        else:
            results['caption_stats']['fallback_template'] += 1
            caption_source = 'template_fallback'
        
        # Get final caption (with fallbacks)
        style_caption = get_style_caption_for_segment(segment_id, style_captions, seg)

        generated_path = os.path.join(
            GENERATED_AUDIO_DIR, f"{segment_id}_gen.wav"
        )

        # Evaluate segment
        seg_result = evaluate_segment(
            model, tokenizer, description_tokenizer, clap_model, clap_processor, device, seg, style_caption, generated_path
        )
        seg_result['caption_source'] = caption_source
        results['segments'].append(seg_result)

        # Collect for aggregation
        if seg_result['l_sem'] is not None:
            l_sem_scores.append(seg_result['l_sem'])

        # Collect audio embedding for L_dyn (using MFCC features)
        if os.path.exists(generated_path):
            try:
                audio_arr, sr = sf.read(generated_path)
                if sr != 48000:
                    audio_arr = librosa.resample(audio_arr, orig_sr=sr, target_sr=48000)
                # Use CLAP audio features for L_dyn
                if clap_model is not None:
                    audio_emb = extract_clap_audio_embedding(clap_model, clap_processor, device, audio_arr)
                    audio_embeddings.append(audio_emb)
            except:
                pass
    
    # Compute L_dyn
    if len(audio_embeddings) >= 2:
        results['l_dyn'] = compute_l_dyn(audio_embeddings)
    
    # Average L_sem
    if l_sem_scores:
        results['l_sem_avg'] = float(np.mean(l_sem_scores))
    
    return results


def run_full_evaluation():
    """Run complete evaluation on all test segments."""

    # Load IndicParler-TTS model
    model, tokenizer, description_tokenizer, device = load_model()
    
    # Load CLAP model for L_sem evaluation
    clap_model, clap_processor = load_clap_model()

    # Load data
    print("\nLoading data...")
    segments = load_test_segments()
    style_captions = load_style_captions()
    stories = group_segments_by_story(segments)

    # Quick test mode
    if QUICK_TEST:
        print(f"\n=== QUICK TEST MODE ===")
        print(f"Testing with Story {QUICK_TEST_STORY}, first {QUICK_TEST_LIMIT} segments")
        stories = {
            QUICK_TEST_STORY: stories[QUICK_TEST_STORY][:QUICK_TEST_LIMIT]
        }

    print(f"Total segments: {sum(len(s) for s in stories.values())}")
    print(f"Stories: {len(stories)}")
    print(f"Style captions available: {len(style_captions)}")

    # Evaluate each story
    all_results = []
    story_summaries = []

    for story_id, story_segs in stories.items():
        result = evaluate_story(model, tokenizer, description_tokenizer, clap_model, clap_processor, device, story_segs, style_captions)
        all_results.append(result)

        story_summaries.append({
            'story_id': story_id,
            'num_segments': len(story_segs),
            'l_dyn': result['l_dyn'],
            'l_sem_avg': result['l_sem_avg'],
            'caption_stats': result['caption_stats'],
        })

    # Save results
    summary_path = os.path.join(OUTPUT_DIR, "evaluation_summary.json")
    with open(summary_path, 'w', encoding='utf-8') as f:
        json.dump({
            'story_summaries': story_summaries,
            'full_results': all_results,
        }, f, indent=2, ensure_ascii=False)

    # Print summary
    print("\n" + "="*70)
    print("EVALUATION SUMMARY")
    print("="*70)

    print(f"\n{'Story':<10} {'Segments':<10} {'L_sem (↑)':<14} {'L_dyn (↓)':<14}")
    print("-"*48)

    for summary in story_summaries:
        l_sem_str = f"{summary['l_sem_avg']:.4f}" if summary['l_sem_avg'] else "N/A"
        l_dyn_str = f"{summary['l_dyn']:.4f}" if summary['l_dyn'] else "N/A"
        print(f"{summary['story_id']:<10} {summary['num_segments']:<10} {l_sem_str:<14} {l_dyn_str:<14}")

    # Overall statistics
    all_l_sem = [s['l_sem_avg'] for s in story_summaries if s['l_sem_avg'] is not None]
    all_l_dyn = [s['l_dyn'] for s in story_summaries if s['l_dyn'] is not None]

    print("\n" + "-"*48)
    print(f"{'OVERALL':<10} {'':<10} {np.mean(all_l_sem):.4f} (avg){'<14'} {np.mean(all_l_dyn):.4f} (avg)")
    print(f"{'':<10} {'':<10} {np.std(all_l_sem):.4f} (std){'<14'} {np.std(all_l_dyn):.4f} (std)")

    # Caption quality summary
    total_gpt4o = sum(s['caption_stats']['gpt4o_generated'] for s in story_summaries)
    total_emotion = sum(s['caption_stats']['fallback_emotion'] for s in story_summaries)
    total_template = sum(s['caption_stats']['fallback_template'] for s in story_summaries)
    total_failed = sum(s['caption_stats']['failed'] for s in story_summaries)
    total_all = total_gpt4o + total_emotion + total_template + total_failed

    print("\n" + "="*70)
    print("CAPTION QUALITY")
    print("="*70)
    print(f"GPT-4o generated:  {total_gpt4o} ({total_gpt4o/total_all*100:.1f}%)")
    print(f"Emotion fallback:  {total_emotion} ({total_emotion/total_all*100:.1f}%)")
    print(f"Template fallback: {total_template} ({total_template/total_all*100:.1f}%)")
    print(f"Failed/missing:    {total_failed} ({total_failed/total_all*100:.1f}%)")
    
    print("\n" + "="*70)
    print(f"Full results saved to: {summary_path}")
    print(f"Generated audio in: {GENERATED_AUDIO_DIR}/")
    print("="*70)
    
    return all_results


# ============================================================================
# Main
# ============================================================================


if __name__ == "__main__":
    print("="*70)
    print("Style Adherence Evaluation for IndicParler-TTS")
    print("Metrics: L_sem (semantic alignment), L_dyn (style smoothness)")
    print("="*70)
    
    run_full_evaluation()
