# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint_best:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.ckpt_dir} # directory to save the model file
  verbose: true # verbosity mode
  save_last: true # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: 1 # save k best models (determined by above metric)
  mode: "max"
  monitor: "Retrieval/val_0/predictions/T2A/R@1"
  auto_insert_metric_name: false # when True, the checkpoints filenames will contain the metric name
  filename: "best_{epoch:02d}_rasa_t2a_r1_{Retrieval/val_0/predictions/T2A/R@1:.3f}"
  save_weights_only: false # if True, then only the model’s weights will be saved
  every_n_epochs: 1 # number of epochs between checkpoints
